In [43]:
#Adding and |Removing Elements In The Arrays
import numpy as np
arr = np.array([10,20,30,40,50,60,70,80])
print(arr)
print(np.append(arr,[33,55]))
print(np.insert(arr,2,[11,22],axis =0))
print(np.delete(arr,[7]))

[10 20 30 40 50 60 70 80]
[10 20 30 40 50 60 70 80 33 55]
[10 20 11 22 30 40 50 60 70 80]
[10 20 30 40 50 60 70]
