In [5]:

arr1 =  ([20,30,40,50])
arr2 =  ([10,10,10,10])
print(arr1+arr2)

[20, 30, 40, 50, 10, 10, 10, 10]


In [24]:
#Concatenation of two arrays 
import numpy as np
arr1 = np.array([[20,30],[40,50]])
arr2 = np.array([[10,10],[10,10]])
print(np.concatenate([arr1,arr2],axis = 1))
print()
print(np.vstack([arr1,arr2]))                #vertical concatenation
print()
print(np.hstack([arr1,arr2]))               #Horizontal concatenation

[[20 30 10 10]
 [40 50 10 10]]

[[20 30]
 [40 50]
 [10 10]
 [10 10]]

[[20 30 10 10]
 [40 50 10 10]]


In [34]:
arr3 = np.array([10,20,30,40,50,60,70,80,90])
print(np.array_split(arr3,2))

[array([10, 20, 30, 40, 50]), array([60, 70, 80, 90])]


In [38]:
arr3 = np.array([[10,20,30,40],[50,60,70,80]])
print(np.array_split(arr3,4))

[array([[10, 20, 30, 40]]), array([[50, 60, 70, 80]]), array([], shape=(0, 4), dtype=int64), array([], shape=(0, 4), dtype=int64)]
